// Pure parsing/serialization for vault markdown — no fs, so it's shared by the
// build-time reader (lib/vault.ts) and the write route handlers.
import matter from "gray-matter";
import type { Task, TaskStatus, TaskPriority, WikiPage } from "./types";

// gray-matter (js-yaml) turns unquoted `2026-06-25` into a JS Date; normalize back.
export function ymd(value: unknown): string {
  if (value == null || value === "") return "";
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  return String(value);
}

export function firstParagraph(body: string, max = 160): string {
  const line = body
    .split("\n")
    .map((l) => l.trim())
    .find((l) => l && !l.startsWith("#") && !l.startsWith("---"));
  if (!line) return "";
  const clean = line.replace(/[*_`>[\]]/g, "");
  return clean.length > max ? clean.slice(0, max) + "…" : clean;
}

// gray-matter (js-yaml) THROWS on malformed YAML frontmatter — e.g. an unquoted
// colon in a summary ("…growing context: fast weights…"). Because wiki/tasks/daily
// files are auto-generated by the ingest, one bad page must never crash the whole
// static build. Fall back to a lenient extraction of simple `key: value` lines so
// the page still loads (title/summary/tags/body intact).
export function safeMatter(raw: string): { data: Record<string, unknown>; content: string } {
  try {
    const parsed = matter(raw);
    return { data: parsed.data as Record<string, unknown>, content: parsed.content };
  } catch {
    const m = raw.match(/^﻿?---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
    if (!m) return { data: {}, content: raw };
    const [, fm, body] = m;
    const data: Record<string, unknown> = {};
    for (const line of fm.split(/\r?\n/)) {
      const kv = line.match(/^([A-Za-z0-9_-]+):\s?(.*)$/);
      if (!kv) continue;
      const v = kv[2].trim();
      data[kv[1]] = /^\[.*\]$/.test(v)
        ? v
            .slice(1, -1)
            .split(",")
            .map((s) => s.trim().replace(/^["']|["']$/g, ""))
            .filter(Boolean)
        : v.replace(/^["']|["']$/g, "");
    }
    return { data, content: body };
  }
}

export function parseWikiPage(slug: string, raw: string): WikiPage {
  const { data, content } = safeMatter(raw);
  return {
    slug,
    title: String(data.title ?? slug),
    summary: String(data.summary ?? firstParagraph(content)),
    tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
    sources: Array.isArray(data.sources) ? data.sources.map(String) : [],
    updated: ymd(data.updated),
    body: content.trim(),
  };
}

export function parseNoteDoc(
  slug: string,
  raw: string,
): { slug: string; title: string; created: string; updated: string; body: string } {
  const { data, content } = safeMatter(raw);
  return {
    slug,
    title: String(data.title ?? slug),
    created: ymd(data.created),
    updated: ymd(data.updated),
    body: content.trim(),
  };
}

export function parseTask(id: string, raw: string): Task {
  const { data, content } = safeMatter(raw);
  const status = (["todo", "in_progress", "done"].includes(String(data.status))
    ? String(data.status)
    : "todo") as TaskStatus;
  const priority = (["high", "medium", "low"].includes(String(data.priority))
    ? String(data.priority)
    : "medium") as TaskPriority;
  return {
    id,
    title: String(data.title ?? id),
    status,
    priority,
    due_date: ymd(data.due_date),
    project: String(data.project ?? "unsorted"),
    tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
    page_slug: data.page_slug ? String(data.page_slug) : "",
    created_at: ymd(data.created_at),
    updated_at: ymd(data.updated_at),
    completed_at: ymd(data.completed_at),
    body: content.trim(),
  };
}

export type ParsedLog = { date: string; action: string; heading: string; body: string };

/** Parse wiki/log.md into entries in FILE order. Each entry is a
 *  `## [YYYY-MM-DD] action | description` heading plus the text under it.
 *  Shared by the build-time reader and the Convex sync; callers decide ordering
 *  (newest-first + limit) and any extra fields (e.g. a stored sort index). */
export function parseLogEntries(raw: string): ParsedLog[] {
  const out: ParsedLog[] = [];
  for (const part of raw.split(/\n(?=##\s)/)) {
    const head = part.match(/^##\s+(.*)$/m);
    if (!head) continue;
    const heading = head[1].trim();
    const dm = heading.match(/\[?(\d{4}-\d{2}-\d{2})\]?\s*([^|]*)/);
    out.push({
      date: dm ? dm[1] : "",
      action: dm && dm[2] ? dm[2].trim() : "",
      heading,
      body: part.replace(/^##\s+.*$/m, "").trim(),
    });
  }
  return out;
}

/** kebab-case task id from a title (stable filename stem). */
export function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || `task-${Date.now()}`
  );
}

/** Build a new wiki/tasks/<id>.md file body in the exact README format. */
export function buildTaskFile(input: {
  title: string;
  project?: string;
  priority?: TaskPriority;
  due_date?: string;
  page_slug?: string;
  tags?: string[];
  today: string;
  body?: string;
}): string {
  const tags = input.tags?.length ? `[${input.tags.join(", ")}]` : "[]";
  return [
    "---",
    `title: ${input.title.trim()}`,
    "status: todo",
    `priority: ${input.priority ?? "medium"}`,
    `due_date: ${input.due_date ?? ""}`,
    `project: ${input.project?.trim() || "unsorted"}`,
    `tags: ${tags}`,
    `page_slug: ${input.page_slug ?? ""}`,
    `created_at: ${input.today}`,
    `updated_at: ${input.today}`,
    "---",
    "",
    (input.body ?? "").trim() || "_Jotted from the web viewer._",
    "",
  ].join("\n");
}
